<a href="https://colab.research.google.com/github/AM0ya/Clase_Programacion/blob/main/Actividad_Calificada_07_Datos_Temporales_269712.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Actividad calificada: Datos temporales**
### Limpieza y transformación de fechas, horas y duraciones en un dataset real

---

| | |
|---|---|
| **Materia** | Programación para Analítica Descriptiva y Predictiva |
| **Programa** | Maestría en Inteligencia Artificial y Analítica de Datos (MIAAD) — UACJ |
| **Unidad** | 02 Análisis Descriptivo de los Datos |
| **Tema** | Limpieza y transformación de datos: datos temporales |
| **Modalidad** | Individual |
| **Valor** | 100 puntos |
| **Dataset** | Viajes de taxi en Nueva York, marzo de 2019 (NYC TLC, muestra publicada en un repositorio público de GitHub) |
| **Fecha de entrega** | 27/09/2026 |

---

## Datos del estudiante

| | |
|---|---|
| **Nombre completo** |Alfredo Moya Orozco |
| **Matrícula** |269712 |

## Instrucciones

1. Trabaja en Google Colab. Guarda una copia en tu Drive (**Archivo → Guardar una copia en Drive**) antes de empezar.
2. Completa tus datos en la tabla anterior.
3. Resuelve las actividades **en orden**: algunas usan variables creadas en actividades anteriores.
4. Escribe tu código en las celdas marcadas con `# Escribe tu código aquí`. Puedes agregar celdas si lo necesitas.
5. **Comenta tu código**: cada bloque debe explicar qué hace y por qué. Los comentarios forman parte de la calificación de cada actividad.
6. Responde las preguntas en las celdas **Respuesta**, con tus propias palabras y apoyándote en tus resultados (cita cifras).
7. Usa los métodos vistos en la sesión: `pd.to_datetime()`, el accesor `.dt`, `pd.Timedelta`, `.between()`, `tz_localize()`, `groupby()`, `sort_values()`, `.where()`, máscaras booleanas, etc.
8. Antes de entregar, ejecuta todo el notebook (**Entorno de ejecución → Reiniciar y ejecutar todo**) y verifica que no haya errores.
9. **Entrega en Moodle** un archivo de texto `Actividad_Temporales_<Matricula>.txt` que contenga el **enlace** a tu notebook (Google Colab o GitHub), con las salidas visibles.
   - Colab: **Compartir → Acceso general → Cualquier persona con el enlace (Lector)**.
   - GitHub: el repositorio debe ser **público**.
   - Opcional: puedes adjuntar también el archivo `.ipynb`.

## Contexto

El dataset contiene 6,433 viajes de taxis amarillos y verdes de la ciudad de Nueva York registrados en **marzo de 2019**. Cada fila es un viaje. Las fechas y horas están en **hora local de Nueva York**.

| Columna | Descripción |
|---|---|
| `pickup` | Fecha y hora en que inicia el viaje |
| `dropoff` | Fecha y hora en que termina el viaje |
| `passengers` | Número de pasajeros |
| `distance` | Distancia recorrida, en **millas** |
| `fare` | Tarifa base (USD) |
| `tip`, `tolls` | Propina y peajes (USD) |
| `total` | Monto total cobrado (USD) |
| `color` | `yellow` o `green` |
| `payment` | Forma de pago |
| `pickup_zone`, `dropoff_zone` | Zona de origen y destino |
| `pickup_borough`, `dropoff_borough` | Distrito de origen y destino |

> **Dato útil**: en Nueva York, el horario de verano de 2019 comenzó el **domingo 10 de marzo**: a las 02:00 el reloj saltó a las 03:00.

## Rúbrica

| Actividad | Puntos | Excelente | Bueno | Insuficiente | No entregado / Incorrecto |
|---|---|---|---|---|---|
| **1. Conversión y validación** | 20 | 18–20: conversión con formato explícito y verificación de `NaT`; viajes fuera de periodo detectados; análisis del cambio de horario correcto; código comentado; conclusión con cifras. | 14–17: resultados correctos con omisiones menores en comentarios o conclusión. | 1–13: conversión sin verificar o validaciones incompletas; conclusión sin sustento. | 0: no se entregó o el código no produce resultados. |
| **2. Duraciones y anomalías** | 25 | 23–25: duración y velocidad calculadas correctamente; anomalías cuantificadas en todas las categorías; criterio de exclusión argumentado con evidencia. | 18–22: cálculos correctos; criterio parcial o con poca evidencia. | 1–17: cálculos con errores o anomalías no cuantificadas. | 0: no se entregó o es incorrecto. |
| **3. Componentes y patrones** | 25 | 23–25: componentes extraídos; viajes que cruzan la medianoche identificados; patrones por hora y día de la semana con `groupby()`; interpretación fundamentada. | 18–22: componentes y agrupaciones correctos; interpretación incompleta. | 1–17: agrupaciones con errores o sin interpretación. | 0: no se entregó o es incorrecto. |
| **4. Dataset limpio y comparación** | 20 | 18–20: dataset limpio construido con el criterio de 2.4 y verificado; comparación entre periodos con filtros temporales correcta; registro de decisión completo. | 14–17: dataset limpio correcto; comparación o registro incompletos. | 1–13: criterio aplicado de forma inconsistente o sin verificación. | 0: no se entregó o es incorrecto. |
| **Reflexión final** | 10 | 9–10: respuestas fundamentadas en los resultados propios. | 7–8: respuestas correctas pero generales. | 1–6: respuestas vagas o sin relación con los resultados. | 0: no se entregó. |
| **Total** | **100** | | | | |

**Notas**:

- Las respuestas escritas de cada actividad (1.4, 2.4, 3.4, 4.3) y los comentarios del código cuentan para la calificación **de esa actividad**, no solo para la reflexión final.
- Si el enlace no abre o requiere solicitar acceso, la actividad se considera no entregada.
- Entrega tardía: se descuenta **5 % por día natural** de retraso, hasta 7 días; después de ese plazo la calificación es 0. El descuento se aplica sobre la calificación obtenida.

## Carga de datos

Ejecuta la siguiente celda. No requiere modificaciones.

In [24]:
import pandas as pd

# Carga del dataset de taxis de Nueva York desde un repositorio público de GitHub.
# El archivo se lee con pandas; no se requiere ninguna otra biblioteca.
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/taxis.csv'
taxis = pd.read_csv(url)

print('Dimensiones:', taxis.shape)
taxis.head()

Dimensiones: (6433, 14)


,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan


---
## Actividad 1. Conversión y validación (20 puntos)

### 1.1 Conversión (5 pts)

1. Muestra el tipo de dato de `pickup` y `dropoff`.
2. Convierte ambas columnas a tipo fecha con `pd.to_datetime()`, indicando el **formato explícito** que corresponde a los valores.
3. Verifica que la conversión no generó `NaT`: compara el número de faltantes antes y después.

In [25]:
# Escribe tu código aquí

#Se revisa el tipo de dato con dtype para las columnas de pickup y dropoff.
print('Tipo de datos antes de conversion\n')
print('tipo de dato de la columna pickup: ',taxis['pickup'].dtype)
print('tipo de dato de la columna dropoff: ',taxis['dropoff'].dtype)
print('\n')
# Cuenta de NaT antes de la conversión
faltantes_antes = taxis[['pickup', 'dropoff']].isna().sum()

#Conversion de datos con pd.to_datetime() para ambas columnas.
taxis['pickup'] = pd.to_datetime(taxis['pickup'], format='%Y-%m-%d %H:%M:%S')
taxis['dropoff'] = pd.to_datetime(taxis['dropoff'], format='%Y-%m-%d %H:%M:%S')

#verificacion de tipo de datos despues de la conversion.
print('Tipo de datos despues de conversion\n')
print('tipo de dato de la columna pickup: ',taxis['pickup'].dtype)
print('tipo de dato de la columna dropoff: ',taxis['dropoff'].dtype)

#Verifica que la conversión no generó NaT
faltantes_despues = taxis[['pickup', 'dropoff']].isna().sum()
print("\nValores faltantes (NaT) antes de la conversión:")
print(faltantes_antes)
print("\nValores faltantes (NaT) después de la conversión:")
print(faltantes_despues)

Tipo de datos antes de conversion

tipo de dato de la columna pickup:  object
tipo de dato de la columna dropoff:  object


Tipo de datos despues de conversion

tipo de dato de la columna pickup:  datetime64[ns]
tipo de dato de la columna dropoff:  datetime64[ns]

Valores faltantes (NaT) antes de la conversión:
pickup     0
dropoff    0
dtype: int64

Valores faltantes (NaT) después de la conversión:
pickup     0
dropoff    0
dtype: int64


### 1.2 Periodo de los datos (5 pts)

El dataset debería contener solo viajes de marzo de 2019.

1. Muestra la fecha mínima y máxima de `pickup` y de `dropoff`.
2. Cuenta y muestra los viajes cuyo `pickup` **no** está en marzo de 2019.
3. ¿Hay viajes con `pickup` en marzo y `dropoff` fuera de marzo? Cuéntalos.

In [26]:
# Escribe tu código aquí

#Muestra la fecha mínima y máxima de pickup y de dropoff
print("Pickup - Mínima:", taxis['pickup'].min(), "| Máxima:", taxis['pickup'].max())
print("Dropoff - Mínima:", taxis['dropoff'].min(), "| Máxima:", taxis['dropoff'].max())

#Cuenta los viajes donde pickup no está en marzo de 2019
fuera_marzo = taxis[~((taxis['pickup'].dt.year == 2019) & (taxis['pickup'].dt.month == 3))]
print(f"\nViajes con pickup fuera de marzo 2019: {len(fuera_marzo)}")

#Viajes con pickup en marzo y dropoff fuera de marzo
pickup_marzo = (taxis['pickup'].dt.year == 2019) & (taxis['pickup'].dt.month == 3)
dropoff_fuera_marzo = ~((taxis['dropoff'].dt.year == 2019) & (taxis['dropoff'].dt.month == 3))
cruzan_mes = taxis[pickup_marzo & dropoff_fuera_marzo]
print(f"Viajes con pickup en marzo y dropoff en otro mes: {len(cruzan_mes)}")

Pickup - Mínima: 2019-02-28 23:29:03 | Máxima: 2019-03-31 23:43:45
Dropoff - Mínima: 2019-02-28 23:32:35 | Máxima: 2019-04-01 00:13:58

Viajes con pickup fuera de marzo 2019: 1
Viajes con pickup en marzo y dropoff en otro mes: 1


### 1.3 Cambio de horario (5 pts)

El 10 de marzo de 2019, en Nueva York, las horas entre 02:00 y 02:59 **no existieron**.

1. Filtra los viajes con `pickup` el 10 de marzo y cuenta cuántos hay en cada hora (`.dt.hour` y `groupby()` o `value_counts()`). ¿Hay viajes a las 2:00?
2. Localiza `pickup` en la zona `'America/New_York'` con `tz_localize()` usando `nonexistent='NaT'` y cuenta cuántos valores quedan como `NaT`.

In [27]:
# Escribe tu código aquí

#Filtrar los viajes con pickup el 10 de marzo y cuenta cuántos hay por hora
march_10 = taxis[taxis['pickup'].dt.date == pd.to_datetime('2019-03-10').date()]
conteo_horas_10 = march_10['pickup'].dt.hour.value_counts().sort_index()
print("Conteo de viajes por hora el 10 de marzo de 2019:")
print(conteo_horas_10)

hay_viajes_2 = 2 in conteo_horas_10.index and conteo_horas_10[2] > 0
print(f"\n¿Hay viajes registrados a las 02:00 horas? {hay_viajes_2}")

#Localiza pickup en 'America/New_York' con 'NaT'
pickup_tz = pd.to_datetime(taxis['pickup']).dt.tz_localize('America/New_York', nonexistent='NaT', ambiguous='NaT')
nat_count = pickup_tz.isna().sum()
print(f"Número de valores NaT generados por tz_localize (hora inexistente): {nat_count}")

Conteo de viajes por hora el 10 de marzo de 2019:
pickup
0     11
1      7
3      6
4      7
5      1
6      2
7      5
8      7
9      9
10    13
11    11
12    17
13     8
14    13
15     9
16    10
17    14
18     7
19     3
20     4
21     3
22    10
23     8
Name: count, dtype: int64

¿Hay viajes registrados a las 02:00 horas? False
Número de valores NaT generados por tz_localize (hora inexistente): 0


### 1.4 Conclusión (5 pts)

¿Qué problemas temporales encontraste en esta actividad? ¿Qué indica el resultado de 1.3 sobre la zona horaria en que están registrados los datos? Responde con cifras.

**Respuesta 1.4:**

Durante la conversión no se encontraron valores faltantes iniciales, y el formato explícito '%Y-%m-%d %H:%M:%S' procesó correctamente todas las filas. Al analizar el 10 de marzo de 2019, se observa que no existen registros a las 02:00 horas debido al salto del horario de verano en Nueva York. Al aplicar tz_localize con nonexistent='NaT', exactamente 0 registros (o los correspondientes si existieran ambigüedades) se marcaron como nulos, lo que confirma de manera contundente que las marcas temporales del dataset están registradas directamente en hora local de Nueva York (America/New_York).

---
## Actividad 2. Duraciones y anomalías (25 puntos)

### 2.1 Duración de cada viaje (6 pts)

1. Crea la columna `duracion` = `dropoff` − `pickup`.
2. Crea `duracion_min` con la duración en **minutos** (usa `.dt.total_seconds()`).
3. Muestra el resumen estadístico de `duracion_min` con `describe()`.

In [28]:
# Escribe tu código aquí

#Crea la columna duracion y duracion_min
taxis['duracion'] = taxis['dropoff'] - taxis['pickup']
taxis['duracion_min'] = taxis['duracion'].dt.total_seconds() / 60

#Muestra el resumen estadístico
print("Resumen estadístico de la duración (minutos):")
print(taxis['duracion_min'].describe())

Resumen estadístico de la duración (minutos):
count    6433.000000
mean       14.349617
std        11.643892
min         0.000000
25%         6.500000
50%        10.900000
75%        18.516667
max       107.666667
Name: duracion_min, dtype: float64


### 2.2 Duraciones anómalas (6 pts)

Cuenta los viajes con:

- Duración **negativa** (termina antes de iniciar).
- Duración **cero**.
- Duración **menor a 1 minuto** (incluye los de duración cero).
- Duración **mayor a 3 horas**.

Muestra los viajes de duración cero con las columnas `pickup`, `dropoff`, `distance`, `fare` y `total`.

In [29]:
# Escribe tu código aquí

# Conteo de anomalías
negativas = (taxis['duracion_min'] < 0).sum()
cero = (taxis['duracion_min'] == 0).sum()
menor_1 = (taxis['duracion_min'] < 1).sum()
mayor_3h = (taxis['duracion_min'] > 180).sum()

print(f"Duración negativa (< 0 min): {negativas}")
print(f"Duración cero (== 0 min): {cero}")
print(f"Duración menor a 1 minuto: {menor_1}")
print(f"Duración mayor a 3 horas (> 180 min): {mayor_3h}")

# Muestra los viajes de duración cero
print("\nViajes con duración cero:")
display(taxis[taxis['duracion_min'] == 0][['pickup', 'dropoff', 'distance', 'fare', 'total']])

Duración negativa (< 0 min): 0
Duración cero (== 0 min): 6
Duración menor a 1 minuto: 72
Duración mayor a 3 horas (> 180 min): 0

Viajes con duración cero:


,pickup,dropoff,distance,fare,total
1690,2019-03-22 06:24:14,2019-03-22 06:24:14,0.0,72.0,72.0
5493,2019-03-06 12:14:00,2019-03-06 12:14:00,0.0,10.0,10.0
5624,2019-03-11 14:04:50,2019-03-11 14:04:50,0.0,2.5,3.3
5638,2019-03-13 12:22:00,2019-03-13 12:22:00,0.0,10.0,10.0
6083,2019-03-19 15:34:00,2019-03-19 15:34:00,0.0,5.0,5.0
6356,2019-03-01 16:58:23,2019-03-01 16:58:23,0.0,3.0,4.8


### 2.3 Velocidad promedio (6 pts)

La velocidad promedio de un viaje, en millas por hora, es `distance / (duracion_min / 60)`.

1. Crea la columna `velocidad_mph` **solo para viajes con duración mayor que cero**; en los demás debe quedar como faltante (`NaN`). Sugerencia: calcula la velocidad para todos los viajes y conserva solo los valores válidos con `.where(condición)`, que deja `NaN` donde la condición es `False`.
2. Cuenta los viajes con velocidad mayor a 60 mph (velocidad poco plausible en tráfico urbano).
3. Muestra los 5 viajes con mayor velocidad, ordenados de mayor a menor, con `pickup`, `dropoff`, `duracion_min`, `distance`, `velocidad_mph` y `fare`.

In [30]:
# Escribe tu código aquí

#Velocidad promedio en mph
taxis['velocidad_mph'] = (taxis['distance'] / (taxis['duracion_min'] / 60)).where(taxis['duracion_min'] > 0)

#Cuenta los viajes con velocidad mayor a 60 mph
vel_alta = (taxis['velocidad_mph'] > 60).sum()
print(f"Viajes con velocidad mayor a 60 mph: {vel_alta}")

#Muestra los 5 viajes con mayor velocidad
print("\nTop 5 viajes con mayor velocidad:")
display(taxis.sort_values(by='velocidad_mph', ascending=False)[['pickup', 'dropoff', 'duracion_min', 'distance', 'velocidad_mph', 'fare']].head(5))

Viajes con velocidad mayor a 60 mph: 11

Top 5 viajes con mayor velocidad:


,pickup,dropoff,duracion_min,distance,velocidad_mph,fare
770,2019-03-02 03:16:59,2019-03-02 03:17:06,0.116667,9.40,4834.285714,2.5
6089,2019-03-17 23:16:34,2019-03-17 23:16:52,0.300000,10.10,2020.000000,12.0
491,2019-03-07 07:11:33,2019-03-07 07:11:39,0.100000,1.60,960.000000,2.5
5284,2019-03-22 06:24:02,2019-03-22 06:24:11,0.150000,1.70,680.000000,2.5
3241,2019-03-24 17:19:27,2019-03-24 17:19:29,0.033333,0.34,612.000000,65.0


### 2.4 Criterio de exclusión (7 pts)

Con base en 1.2, 2.2 y 2.3, define qué viajes excluirías del análisis y por qué. Considera:

a) ¿Todos los viajes de menos de 1 minuto son errores? Observa su distancia y tarifa.

b) ¿Qué umbrales (duración, velocidad, periodo) usarás? Justifícalos.

**Respuesta 2.4:**

a) Duraciones menores a 1 minuto con distancia cero o tarifas nulas: Aunque algunos viajes muy cortos pueden ocurrir, aquellos con velocidad infinita o cero distancia física son inconsistentes.

b) Duraciones mayores a 3 horas (> 180 min) y velocidades promedio superiores a 60 mph: En el tráfico urbano denso de Nueva York, mantener una velocidad promedio superior a 60 mph sostenida en un viaje largo no es realista y apunta a errores de GPS o viajes que quedaron abiertos por error del conductor. Asimismo, se filtrarán aquellos registros cuyo pickup quede fuera del mes de marzo de 2019.

---
## Actividad 3. Componentes y patrones (25 puntos)

### 3.1 Extraer componentes (6 pts)

Crea las columnas:

- `hora`: hora de `pickup`.
- `dia_num`: día de la semana de `pickup` (lunes = 0).
- `dia_nombre`: nombre del día de `pickup`.
- `fin_semana`: `True` si es sábado o domingo.
- `fecha`: solo la fecha (sin hora) de `pickup`.
- `cruza_medianoche`: `True` si la **fecha** de `dropoff` es distinta de la de `pickup`.

Cuenta cuántos viajes cruzan la medianoche.

In [31]:
# Escribe tu código aquí

taxis['hora'] = taxis['pickup'].dt.hour
taxis['dia_num'] = taxis['pickup'].dt.dayofweek
taxis['dia_nombre'] = taxis['pickup'].dt.day_name()
taxis['fin_semana'] = taxis['dia_num'].isin([5, 6])
taxis['fecha'] = taxis['pickup'].dt.date
taxis['cruza_medianoche'] = taxis['dropoff'].dt.date != taxis['pickup'].dt.date

print(f"Número de viajes que cruzan la medianoche: {taxis['cruza_medianoche'].sum()}")

Número de viajes que cruzan la medianoche: 50


### 3.2 Patrón por hora del día (7 pts)

Con `groupby('hora')`, calcula para cada hora: el **número de viajes** y la **mediana** de `duracion_min`. Indica la hora con más viajes y la hora con menos.

Usa la mediana (no la media) porque la duración tiene valores extremos.

In [32]:
# Escribe tu código aquí

patron_hora = taxis.groupby('hora').agg(
    num_viajes=('pickup', 'count'),
    duracion_mediana=('duracion_min', 'median')
)
print(patron_hora)

hora_mas = patron_hora['num_viajes'].idxmax()
hora_menos = patron_hora['num_viajes'].idxmin()
print(f"\nHora con más viajes: {hora_mas} ({patron_hora.loc[hora_mas, 'num_viajes']} viajes)")
print(f"Hora con menos viajes: {hora_menos} ({patron_hora.loc[hora_menos, 'num_viajes']} viajes)")

      num_viajes  duracion_mediana
hora                              
0            205         10.733333
1            110          9.633333
2            101          9.183333
3             67          9.583333
4             57         10.500000
5             51          8.700000
6            142          7.833333
7            221          9.583333
8            313         11.316667
9            319         11.616667
10           325         11.883333
11           295         12.033333
12           334         12.775000
13           316         10.558333
14           360         11.841667
15           330         12.058333
16           336         11.583333
17           388         11.975000
18           417         11.100000
19           406         10.650000
20           368          9.258333
21           355         11.083333
22           321          9.816667
23           296         10.575000

Hora con más viajes: 18 (417 viajes)
Hora con menos viajes: 5 (51 viajes)


### 3.3 Patrón por día de la semana (6 pts)

Calcula por día de la semana el **número de viajes** y la **mediana** de `duracion_min` y de `fare`. Presenta los días en orden de lunes a domingo (sugerencia: agrupa por `['dia_num', 'dia_nombre']`).

Toma en cuenta que marzo de 2019 no tiene el mismo número de cada día de la semana: calcula también el **promedio de viajes por fecha**, dividiendo entre el número de fechas distintas de ese día de la semana (usa la columna `fecha` y `.nunique()`).

In [33]:
# Escribe tu código aquí

patron_dia = taxis.groupby(['dia_num', 'dia_nombre']).agg(
    num_viajes=('pickup', 'count'),
    duracion_mediana=('duracion_min', 'median'),
    fare_mediana=('fare', 'median'),
    fechas_distintas=('fecha', 'nunique')
).reset_index()

patron_dia['promedio_viajes_fecha'] = patron_dia['num_viajes'] / patron_dia['fechas_distintas']
print(patron_dia[['dia_nombre', 'num_viajes', 'fechas_distintas', 'promedio_viajes_fecha', 'duracion_mediana', 'fare_mediana']])

  dia_nombre  num_viajes  fechas_distintas  promedio_viajes_fecha  \
0     Monday         708                 4                 177.00   
1    Tuesday         825                 4                 206.25   
2  Wednesday         966                 4                 241.50   
3   Thursday         905                 5                 181.00   
4     Friday        1115                 5                 223.00   
5   Saturday        1046                 5                 209.20   
6     Sunday         868                 5                 173.60   

   duracion_mediana  fare_mediana  
0         10.541667           9.5  
1         11.216667           9.5  
2         11.291667           9.5  
3         11.766667           9.5  
4         11.150000           9.5  
5         10.466667           9.0  
6          9.983333           9.0  


### 3.4 Interpretación (6 pts)

a) ¿Qué patrones observas por hora y por día? ¿Coinciden la hora con más viajes y la hora con mayor duración mediana? ¿Qué podría explicarlo?

b) ¿Por qué fue necesario calcular el promedio de viajes por fecha en 3.3 en lugar de comparar solo el total por día de la semana?

**Respuesta 3.4:**

a) Se observa que la demanda de taxis incrementa notablemente en las horas pico de la tarde y disminuye en la madrugada. La hora con más viajes no siempre coincide exactamente con la hora de mayor duración mediana, ya que en las horas pico la congestión vehicular ralentiza los trayectos, elevando la duración mediana incluso cuando el volumen de viajes empieza a descender.

b) Fue necesario calcular el promedio de viajes por fecha (normalizando entre el conteo de días únicos) porque en un mes calendario los días de la semana no ocurren el mismo número de veces (por ejemplo, marzo de 2019 puede tener cinco viernes pero cuatro sábados); comparar solo el total bruto habría sesgado la comparación entre días.

---
## Actividad 4. Dataset limpio y comparación (20 puntos)

### 4.1 Dataset limpio (6 pts)

Crea `taxis_limpio` aplicando el criterio que definiste en 2.4. Imprime cuántos viajes se excluyeron por cada condición y en total, y verifica que `taxis_limpio` cumple todas las condiciones.

In [34]:
# Escribe tu código aquí

# Aplicar criterio de exclusión
condicion_limpieza = (
    (taxis['pickup'].dt.year == 2019) &
    (taxis['pickup'].dt.month == 3) &
    (taxis['duracion_min'] > 0) &
    (taxis['duracion_min'] <= 180) &
    (taxis['velocidad_mph'] <= 60)
)

taxis_limpio = taxis[condicion_limpieza].copy()

total_original = len(taxis)
total_limpio = len(taxis_limpio)
excluidos = total_original - total_limpio

print(f"Total original de registros: {total_original}")
print(f"Total en dataset limpio: {total_limpio}")
print(f"Total de registros excluidos: {excluidos}")

Total original de registros: 6433
Total en dataset limpio: 6415
Total de registros excluidos: 18


### 4.2 Comparación entre periodos (6 pts)

Con `taxis_limpio`, compara los viajes que inician entre las **7:00 y las 9:59** en **días hábiles** contra los del **mismo horario en fin de semana**. Para cada grupo reporta: número de viajes, mediana de `duracion_min` y mediana de `velocidad_mph`.

In [35]:
# Escribe tu código aquí

habiles_7_9 = taxis_limpio[~taxis_limpio['fin_semana'] & (taxis_limpio['hora'].between(7, 9))]
finsemana_7_9 = taxis_limpio[taxis_limpio['fin_semana'] & (taxis_limpio['hora'].between(7, 9))]

def reportar_metricas(df_sub, nombre):
    print(f"--- {nombre} ---")
    print(f"Número de viajes: {len(df_sub)}")
    print(f"Mediana de duración: {df_sub['duracion_min'].median():.2f} minutos")
    print(f"Mediana de velocidad: {df_sub['velocidad_mph'].median():.2f} mph\n")

reportar_metricas(habiles_7_9, "Días hábiles (07:00 - 09:59)")
reportar_metricas(finsemana_7_9, "Fin de semana (07:00 - 09:59)")

--- Días hábiles (07:00 - 09:59) ---
Número de viajes: 687
Mediana de duración: 11.97 minutos
Mediana de velocidad: 9.09 mph

--- Fin de semana (07:00 - 09:59) ---
Número de viajes: 163
Mediana de duración: 7.63 minutos
Mediana de velocidad: 13.47 mph



### 4.3 Registro de decisión (8 pts)

Redacta el registro de la limpieza realizada, como lo documentarías en un proyecto real. Incluye:

- **Conversión**: formato utilizado y verificación.
- **Zona horaria**: en qué zona están los datos y cómo lo verificaste.
- **Criterio de exclusión**: condiciones, umbrales y justificación.
- **Resultado**: viajes antes, después y excluidos.
- **Hallazgo de 4.2** y **limitaciones** del análisis.

**Respuesta 4.3:**

Conversión: Se utilizó pd.to_datetime() con el formato explícito '%Y-%m-%d %H:%M:%S', verificando que no se generaran valores NaT.

Zona horaria: Se confirmó que los datos están en hora local de Nueva York analizando la ausencia de registros durante la transición del horario de verano el 10 de marzo de 2019.

Criterio de exclusión: Se eliminaron viajes con duraciones menores o iguales a cero, duraciones mayores a 3 horas, velocidades promedio superiores a 60 mph y registros fuera de marzo de 2019.

Resultado: De un total inicial de 6,433 registros, se excluyó una minoría de viajes anómalos, conservando un dataset limpio y consistente para el modelado.

Hallazgo: Los viajes matutinos en días hábiles presentan menor velocidad mediana y mayor duración en comparación con el mismo horario en fin de semana, reflejando el tráfico característico de hora pico laboral. Una limitación es que el dataset es una muestra limitada y no abarca todas las condiciones climáticas o estacionales del año.

---
## Reflexión final (10 puntos)

1. ¿Qué ventajas tuvo indicar el formato explícito en 1.1 frente a dejar que pandas lo infiera? ¿En qué situación la inferencia habría producido errores silenciosos?
2. Supón que `pickup` se hubiera registrado en UTC y `dropoff` en hora local de Nueva York. ¿Qué efecto tendría en las duraciones calculadas? ¿Cómo lo habrías detectado con las herramientas de esta actividad?
3. Si se entrenara un modelo para predecir la duración de un viaje, ¿qué problemas causarían las anomalías temporales que encontraste si no se limpiaran?

**Respuesta final:**

Indicar el formato explícito evita que Pandas adivine el formato mediante heurísticas costosas y propensas a errores (como confundir el día y el mes en formatos internacionales DD/MM vs MM/DD), previniendo errores silenciosos en fechas ambiguas.

Si pickup estuviera en UTC y dropoff en hora local, las duraciones calculadas estarían severamente distorsionadas (agregando o restando erróneamente las horas de diferencia de la zona horaria), generando duraciones negativas masivas o valores absurdamente altos que habrían sido detectados inmediatamente en la fase de validación de anomalías de la Actividad 2.

Las anomalías temporales (duraciones cero, negativas o velocidades imposibles) introducirían ruido severo y sesgos graves en un modelo predictivo, degradando su capacidad de generalización y arrojando predicciones erróneas de tiempos de viaje.

---
**Fin de la actividad.** Antes de entregar: **Reiniciar y ejecutar todo**, verificar que no haya errores, guardar con las salidas visibles y comprobar que el enlace abre sin iniciar sesión.